version: "3"
services:
  container1:
    build:
      context: ../
      args:
        - USERNAME=user1
        - PASSWORD=pass1
    ports:
      - "2222:22"
    hostname: container1
  container2:
    build:
      context: ../
      args:
        - USERNAME=user2
        - PASSWORD=pass2
    ports:
      - "2223:22"
    hostname: container2
