version: "3"
services:
  container1:
    build:
      context: ./
      args:
        - USERNAME=user
        - PASSWORD=pass
    hostname: bnsap
    ports:
      - "2222:22"
    volumes:
      - ./:/home/user/ansible
