- hosts: localhost
  vars:
    - ansible_user: "{{ lookup('env', 'USER') }}"
    - ansible_user_password: "pass"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/git.yml
    - include: tasks/tmux.yml
    - include: tasks/zsh-setup.yml

