- name: Install Git
  apt: name=git
  become: true
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "bnsapa2000@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Bal Narendra Sapa"
  tags:
  - git-personal